name: CI with Cache

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache dependencies
        id: cache        #  give this step an id
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-39faf38

      - name: prime-cache-39faf38
        run: |
              echo 'Cache result: ${{ steps.cache.outputs.cache-hit }}'
